const canvas = document.querySelector('#gameCanvas');
const ctx = canvas.getContext('2d');
const scoreEl = document.querySelector('#score');
const highScoreEl = document.querySelector('#highScore');
const livesEl = document.querySelector('#lives');
const message = document.querySelector('#message');
const messageTitle = document.querySelector('#messageTitle');
const startButton = document.querySelector('#startButton');
const cellSize = 24;
const maze = ['#####################','#.........#.........#','#.###.###.#.###.###.#','#o#...#...#...#...#o#','#.###.#.#####.#.###.#','#.....#...#...#.....#','#####.###.#.###.#####','#...................#','#####.###.#.###.#####','#.....#...#...#.....#','#.###.#.#####.#.###.#','#o#...#...#...#...#o#','#.###.###.#.###.###.#','#.........#.........#','#####################'];
const rows = maze.length;
const columns = 21;
const directions = { ArrowUp: [-1, 0], w: [-1, 0], ArrowDown: [1, 0], s: [1, 0], ArrowLeft: [0, -1], a: [0, -1], ArrowRight: [0, 1], d: [0, 1] };
const levels = { easy: { label: 'EASY MODE', ghosts: 1, speed: 330 }, medium: { label: 'MEDIUM MODE', ghosts: 2, speed: 235 }, hard: { label: 'HARD MODE', ghosts: 3, speed: 155 } };
const ghostBlueprints = [{ color: '#db5147', start: [7, 9], algorithm: 'A*' }, { color: '#e1819d', start: [7, 10], algorithm: 'BFS' }, { color: '#5683c2', start: [7, 11], algorithm: 'DFS' }];
let level = 'easy'; let pellets; let pacman; let ghosts; let score; let lives; let highScore = Number(localStorage.getItem('pacmanHighScore') || 0); let state = 'ready'; let frightened = 0; let timer;
const point = (row, column) => ({ row, column });
const cellKey = cell => `${cell.row},${cell.column}`;
const open = (row, column) => row >= 0 && row < rows && column >= 0 && column < columns && maze[row][column] !== '#';
const neighbors = cell => [[-1,0],[1,0],[0,-1],[0,1]].map(([row, column]) => point(cell.row + row, cell.column + column)).filter(next => open(next.row, next.column));
const same = (first, second) => first.row === second.row && first.column === second.column;
const distance = (first, second) => Math.abs(first.row - second.row) + Math.abs(first.column - second.column);
function buildPath(parents, end) { const path = []; let current = end; while (current) { path.unshift(current); current = parents.get(cellKey(current)); } return path.slice(1); }
function search(start, target, type) { const frontier = [{ cell: start, cost: 0 }]; const parents = new Map([[cellKey(start), null]]); const costs = new Map([[cellKey(start), 0]]); while (frontier.length) { frontier.sort((first, second) => type === 'A*' ? first.cost + distance(first.cell, target) - second.cost - distance(second.cell, target) : 0); const current = type === 'DFS' ? frontier.pop().cell : frontier.shift().cell; if (same(current, target)) return buildPath(parents, current); neighbors(current).forEach(next => { const nextKey = cellKey(next); if (!parents.has(nextKey)) { parents.set(nextKey, current); costs.set(nextKey, costs.get(cellKey(current)) + 1); frontier.push({ cell: next, cost: costs.get(nextKey) }); } }); } return []; }
function reset() { pellets = new Map(); maze.forEach((row, rowIndex) => [...row].forEach((cell, columnIndex) => { if (cell === '.' || cell === 'o') pellets.set(`${rowIndex},${columnIndex}`, cell === 'o' ? 2 : 1); })); pacman = { row: 13, column: 9, direction: [0, 0], nextDirection: [0, 0] }; ghosts = ghostBlueprints.slice(0, levels[level].ghosts).map(ghost => ({ ...ghost, row: ghost.start[0], column: ghost.start[1] })); score = 0; lives = 3; frightened = 0; state = 'ready'; window.clearInterval(timer); updateHud(); showMessage('READY?', 'PLAY GAME'); draw(); }
function showMessage(title, buttonText) { messageTitle.textContent = title; startButton.textContent = buttonText; message.classList.remove('hidden'); }
function hideMessage() { message.classList.add('hidden'); }
function updateHud() { scoreEl.textContent = String(score).padStart(6, '0'); highScoreEl.textContent = String(Math.max(score, highScore)).padStart(6, '0'); livesEl.textContent = lives ? '● '.repeat(lives).trim() : 'GAME OVER'; }
function start() { if (state === 'playing') return; if (state === 'won' || state === 'lost') reset(); state = 'playing'; hideMessage(); updateHud(); timer = window.setInterval(tick, levels[level].speed); }
function movePacman(direction) { if (state !== 'playing') return; pacman.nextDirection = direction; }
function movePlayer() { const desired = point(pacman.row + pacman.nextDirection[0], pacman.column + pacman.nextDirection[1]); if (open(desired.row, desired.column)) pacman.direction = pacman.nextDirection; const next = point(pacman.row + pacman.direction[0], pacman.column + pacman.direction[1]); if (open(next.row, next.column)) { pacman.row = next.row; pacman.column = next.column; } const pellet = pellets.get(`${pacman.row},${pacman.column}`); if (pellet) { pellets.delete(`${pacman.row},${pacman.column}`); score += pellet === 2 ? 50 : 10; if (pellet === 2) frightened = 35; if (!pellets.size) endGame(true); } }
function moveGhost(ghost) { if (frightened) { const choices = neighbors(ghost).filter(cell => !same(cell, pacman)); const choice = choices[Math.floor(Math.random() * choices.length)]; if (choice) Object.assign(ghost, choice); return; } const target = point(pacman.row, pacman.column); const path = search(point(ghost.row, ghost.column), target, ghost.algorithm); if (path[0]) Object.assign(ghost, path[0]); }
function collisions() { ghosts.forEach(ghost => { if (ghost.row === pacman.row && ghost.column === pacman.column) { if (frightened) { score += 200; ghost.row = ghost.start[0]; ghost.column = ghost.start[1]; } else { lives--; if (lives) { pacman.row = 13; pacman.column = 9; pacman.direction = [0,0]; pacman.nextDirection = [0,0]; ghosts.forEach(resetGhost => { resetGhost.row = resetGhost.start[0]; resetGhost.column = resetGhost.start[1]; }); } else endGame(false); } } }); }
function endGame(won) { window.clearInterval(timer); state = won ? 'won' : 'lost'; highScore = Math.max(highScore, score); localStorage.setItem('pacmanHighScore', highScore); updateHud(); showMessage(won ? 'YOU WIN!' : 'GAME OVER', 'PLAY AGAIN'); }
function tick() { if (state !== 'playing') return; movePlayer(); ghosts.forEach(moveGhost); collisions(); if (frightened) frightened--; updateHud(); draw(); }
function draw() { canvas.width = columns * cellSize; canvas.height = rows * cellSize; ctx.fillStyle = '#101b2a'; ctx.fillRect(0, 0, canvas.width, canvas.height); maze.forEach((row, rowIndex) => [...row].forEach((cell, columnIndex) => { if (cell === '#') { ctx.fillStyle = '#244b75'; ctx.fillRect(columnIndex * cellSize + 1, rowIndex * cellSize + 1, cellSize - 2, cellSize - 2); ctx.strokeStyle = '#3777a8'; ctx.strokeRect(columnIndex * cellSize + 4, rowIndex * cellSize + 4, cellSize - 8, cellSize - 8); } })); pellets.forEach((type, value) => { const [row, column] = value.split(',').map(Number); ctx.fillStyle = type === 2 ? '#efc658' : '#f5f1e8'; ctx.beginPath(); ctx.arc(column * cellSize + 12, row * cellSize + 12, type === 2 ? 5 : 2.5, 0, Math.PI * 2); ctx.fill(); }); drawPacman(); ghosts.forEach(drawGhost); }
function drawPacman() { const x = pacman.column * cellSize + 12; const y = pacman.row * cellSize + 12; ctx.fillStyle = '#efc658'; ctx.beginPath(); ctx.arc(x, y, 9, 0, Math.PI * 2); ctx.fill(); }
function drawGhost(ghost) { const x = ghost.column * cellSize + 12; const y = ghost.row * cellSize + 12; ctx.fillStyle = frightened ? '#4774a4' : ghost.color; ctx.beginPath(); ctx.arc(x, y - 1, 9, Math.PI, 0); ctx.lineTo(x + 9, y + 8); ctx.lineTo(x + 4, y + 5); ctx.lineTo(x, y + 8); ctx.lineTo(x - 4, y + 5); ctx.lineTo(x - 9, y + 8); ctx.closePath(); ctx.fill(); }
document.querySelectorAll('.level').forEach(button => button.addEventListener('click', () => { level = button.dataset.level; document.querySelectorAll('.level').forEach(item => item.classList.toggle('active', item === button)); reset(); }));
window.addEventListener('keydown', event => { const direction = directions[event.key] || directions[event.key.toLowerCase()]; if (direction) { event.preventDefault(); movePacman(direction); } });
startButton.addEventListener('click', start); reset();
